// ─── ALTERNATIVE AIs DATA ────────────────────────────────────────────────────
// Kaynak: yapay_zeka_alternatifleri.md + kurumsal bilgi katkısı

export type AltTag =
  | 'Ücretsiz'
  | 'Açık Kaynak'
  | 'Yerel Çalışır'
  | 'Gizlilik Odaklı'
  | 'Türkçe Destekli'
  | 'Akademik'
  | 'Hızlı'
  | 'Çok Dilli'
  | 'Ücretli'
  | 'API'
  | 'Tarayıcı'
  | 'Mobil'
  | 'Kurumsal'

export type AltCategory =
  | 'sohbet'
  | 'kod'
  | 'gorsel'
  | 'ses'
  | 'yerel'
  | 'acik-kaynak'
  | 'arastirma'

export interface Alternative {
  name: string
  slug?: string          // tools tablosundaki slug (varsa linke bağlanır)
  website: string
  description: string
  highlight: string      // tek cümle öne çıkan özellik
  tags: AltTag[]
  category: AltCategory
  openSource?: boolean
  addedByUs?: boolean    // dosyada yoktu, biz ekledik
}

// ─── SOHBET & GENEL ASISTAN ───────────────────────────────────────────────────
export const SOHBET_ALTERNATIVES: Alternative[] = [
  {
    name: 'DeepSeek',
    website: 'https://chat.deepseek.com',
    description: 'Çin kaynaklı DeepSeek-V3 ve R1 modelleriyle GPT-4 seviyesinde performans sunan, açık ağırlıklı ve büyük ölçüde ücretsiz AI asistan. Akademik ve teknik konularda özellikle güçlü.',
    highlight: 'GPT-4o seviyesi performans, büyük ölçüde ücretsiz',
    tags: ['Ücretsiz', 'Açık Kaynak', 'Türkçe Destekli', 'API'],
    category: 'sohbet',
    openSource: true,
  },
  {
    name: 'Mistral Le Chat',
    website: 'https://chat.mistral.ai',
    description: 'Avrupa merkezli Mistral AI\'ın geliştirdiği, GDPR uyumlu ve gizlilik odaklı sohbet asistanı. Mixtral modelinin güçlü çok dilli yetenekleri Avrupa kullanıcıları için ideal.',
    highlight: 'Avrupa gizlilik standartları, GDPR tam uyumlu',
    tags: ['Ücretsiz', 'Gizlilik Odaklı', 'Çok Dilli', 'API'],
    category: 'sohbet',
  },
  {
    name: 'Grok',
    website: 'https://grok.x.ai',
    description: 'xAI (Elon Musk) tarafından geliştirilen, X/Twitter\'a entegre gerçek zamanlı web erişimi olan AI asistan. Güncel haberler ve sosyal medya bağlamı gerektiren sorgularda öne çıkar.',
    highlight: 'X/Twitter verisi ile gerçek zamanlı güncel bilgi',
    tags: ['Ücretsiz', 'Hızlı', 'Açık Kaynak'],
    category: 'sohbet',
  },
  {
    name: 'Meta AI (Llama)',
    website: 'https://meta.ai',
    description: 'Meta\'nın Llama 3.1 modelini kullanan AI asistan. WhatsApp, Instagram ve Facebook\'a entegre; aynı zamanda açık kaynak modeller olarak indirip yerel çalıştırılabilir.',
    highlight: 'WhatsApp ve Instagram ile entegre, tamamen ücretsiz',
    tags: ['Ücretsiz', 'Açık Kaynak', 'Çok Dilli', 'Mobil'],
    category: 'sohbet',
    openSource: true,
  },
  {
    name: 'Qwen (Alibaba)',
    website: 'https://chat.qwen.ai',
    description: 'Alibaba Cloud\'un Qwen2.5 modelleri üzerine kurulu, Çince ve İngilizce optimizasyonu yüksek, kod ve matematik yetenekleri güçlü AI asistan.',
    highlight: 'Çince-İngilizce ikili dil optimizasyonu, matematik uzmanlığı',
    tags: ['Ücretsiz', 'Çok Dilli', 'Açık Kaynak', 'API'],
    category: 'sohbet',
    openSource: true,
  },
  {
    name: 'Kimi (Moonshot AI)',
    website: 'https://kimi.ai',
    description: 'Moonshot AI\'ın geliştirdiği 128K token bağlam pencereli, uzun belge analizi ve kod yetenekleri güçlü AI asistan. Claude\'a doğrudan rakip konumunda.',
    highlight: '128K token bağlam penceresi, uzun belge analizi',
    tags: ['Ücretsiz', 'Hızlı', 'Çok Dilli'],
    category: 'sohbet',
  },
  {
    name: 'DuckDuckGo AI Chat',
    website: 'https://duckduckgo.com/aichat',
    description: 'Gizliliği ön planda tutan DuckDuckGo\'nun anonim AI sohbet hizmeti. GPT-4o Mini, Claude, Llama ve Mixtral modelleri arasından seçim yapılabilir; sohbet geçmişi kaydedilmez.',
    highlight: 'Sohbet kaydı yok, hesap gerektirmez, tamamen anonim',
    tags: ['Ücretsiz', 'Gizlilik Odaklı', 'Tarayıcı'],
    category: 'sohbet',
  },
  {
    name: 'Poe',
    website: 'https://poe.com',
    description: 'Quora\'nın geliştirdiği, aynı platformda GPT-4, Claude, Gemini, Llama ve yüzlerce topluluk botuna erişim sunan AI asistan toplayıcısı. Modelleri karşılaştırmak için pratik.',
    highlight: 'Tek platformda 100+ AI modeli: GPT, Claude, Gemini, Llama',
    tags: ['Ücretsiz', 'Hızlı', 'Mobil'],
    category: 'sohbet',
  },
  {
    name: 'Amazon Nova',
    website: 'https://aws.amazon.com/ai/nova',
    description: 'Amazon\'un AWS altyapısı üzerine kurulu Nova model ailesi. Nova Micro, Lite ve Pro seviyeleriyle çok modlu işlem yapabilir; AWS entegrasyonu gerektiren kurumsal kullanım için.',
    highlight: 'AWS ekosistemi ile tam entegrasyon, kurumsal güvenlik',
    tags: ['API', 'Kurumsal', 'Çok Dilli'],
    category: 'sohbet',
  },
  {
    name: 'Venice AI',
    website: 'https://venice.ai',
    description: 'Blockchain tabanlı gizlilik altyapısı kullanan, sohbet geçmişini şifreli saklayan AI platformu. Yerel model seçeneğiyle veri egemenliği isteyen kullanıcılar için.',
    highlight: 'Blockchain şifrelemeli veri saklama, tam gizlilik',
    tags: ['Gizlilik Odaklı', 'Ücretsiz'],
    category: 'sohbet',
  },
  {
    name: 'Yi AI (01.ai)',
    website: 'https://01.ai',
    description: 'Çinli yapay zeka araştırmacısı Kai-Fu Lee liderliğindeki 01.ai\'ın geliştirdiği, uzun bağlam ve çok dilli yetenekleriyle öne çıkan Yi model ailesi.',
    highlight: '200K token bağlam, Türkçe dahil 70+ dil',
    tags: ['Ücretsiz', 'Çok Dilli', 'Açık Kaynak'],
    category: 'sohbet',
    openSource: true,
  },
  {
    name: 'MiniMax Agent',
    website: 'https://agent.minimax.chat',
    description: 'MiniMax\'ın uzun video ve ses anlayan ajan modeli. 1M token bağlam desteğiyle tam film veya ders kaydı analizi yapabilen, Çin kaynaklı çok modlu AI.',
    highlight: '1M token bağlam, video + ses + metin anlama',
    tags: ['Ücretsiz', 'Hızlı', 'Çok Dilli'],
    category: 'sohbet',
  },
  {
    name: 'Brave Leo',
    website: 'https://brave.com/leo',
    description: 'Brave tarayıcısına entegre, Mixtral ve Llama modelleriyle çalışan, tarayıcı içeriğini anlayan AI asistan. Reklamsız, kayıt gerektirmez.',
    highlight: 'Tarayıcı içeriğiyle konuşma, reklamsız, kayıt yok',
    tags: ['Ücretsiz', 'Gizlilik Odaklı', 'Tarayıcı'],
    category: 'sohbet',
  },
  {
    name: 'Lumo by Proton',
    website: 'https://proton.me/lumo',
    description: 'Proton\'ın (ProtonMail/VPN) gizlilik ekosisteminden gelen, İsviçre yasal güvenceleri altında veri işleyen AI asistan. Sağlık ve hukuk gibi hassas alanlarda tercih edilir.',
    highlight: 'İsviçre veri yasaları, Proton şifrelemesi ile korunan AI',
    tags: ['Gizlilik Odaklı', 'Ücretsiz', 'Kurumsal'],
    category: 'sohbet',
    addedByUs: false,
  },
  {
    name: 'Z.ai (Zhipu AI)',
    website: 'https://z.ai',
    description: 'Tsinghua Üniversitesi kökenli Zhipu AI\'ın GLM modeli üzerine kurulu sohbet platformu. Çince akademik metinler ve teknik dökümanlar için özel optimize.',
    highlight: 'Çince akademik metin ve teknik içerik uzmanlığı',
    tags: ['Ücretsiz', 'Çok Dilli', 'Akademik'],
    category: 'sohbet',
  },
  {
    name: 'Chatbox AI',
    website: 'https://chatboxai.app',
    description: 'Masaüstü uygulama olarak çalışan, kendi API anahtarını getir (BYOK) modeliyle OpenAI, Claude, Gemini ve yerel modellere bağlanabilen açık kaynak AI istemcisi.',
    highlight: 'Kendi API anahtarınla çalış, yerel depolama, BYOK',
    tags: ['Ücretsiz', 'Açık Kaynak', 'Yerel Çalışır', 'Gizlilik Odaklı'],
    category: 'sohbet',
    openSource: true,
  },
  // Bizim katkımız ─────────────────────────────────────────────────────────────
  {
    name: 'LM Studio',
    website: 'https://lmstudio.ai',
    description: 'Masaüstünde Llama, Mistral, Gemma ve onlarca açık modeli HuggingFace\'den indirip yerel olarak çalıştırmayı sağlayan en kullanıcı dostu arayüz. Kurulum sıfır, internet bağlantısı gerekmez.',
    highlight: 'Herhangi bir açık modeli tek tıkla indir ve çalıştır',
    tags: ['Ücretsiz', 'Açık Kaynak', 'Yerel Çalışır', 'Gizlilik Odaklı'],
    category: 'yerel',
    openSource: true,
    addedByUs: true,
  },
  {
    name: 'HuggingChat',
    website: 'https://huggingface.co/chat',
    description: 'HuggingFace\'in barındırdığı, Llama 3, Mixtral, Zephyr ve topluluğun en iyi açık modellerini test etmek için ücretsiz chat arayüzü. Model değiştirme çok kolay.',
    highlight: 'HuggingFace\'deki tüm açık modelleri ücretsiz test et',
    tags: ['Ücretsiz', 'Açık Kaynak', 'API'],
    category: 'sohbet',
    openSource: true,
    addedByUs: true,
  },
  {
    name: 'Cohere Command',
    website: 'https://cohere.com',
    description: 'Kurumsal RAG (Retrieval Augmented Generation) ve doküman arama için özelleşmiş AI platformu. Şirket içi belgeleri AI ile sorgulama konusunda sektör standardı.',
    highlight: 'Kurumsal RAG ve şirket içi doküman AI araması',
    tags: ['API', 'Kurumsal', 'Türkçe Destekli'],
    category: 'sohbet',
    addedByUs: true,
  },
]

// ─── KODLAMA ARAÇLARI ─────────────────────────────────────────────────────────
export const KOD_ALTERNATIVES: Alternative[] = [
  {
    name: 'Windsurf Editor',
    website: 'https://codeium.com/windsurf',
    description: 'Codeium\'un geliştirdiği, tüm proje bağlamını anlayan "Cascade" ajanıyla çoklu dosya düzenleme yapabilen AI-native kod editörü. Cursor\'a en güçlü alternatif.',
    highlight: 'Cascade ajanı: çok dosyayı aynı anda düzeltir',
    tags: ['Ücretsiz', 'Hızlı'],
    category: 'kod',
  },
  {
    name: 'Void',
    website: 'https://voideditor.com',
    description: 'VS Code\'u çatallayarak geliştirilen, Cursor\'un açık kaynak alternatifi. Tüm AI sağlayıcılarına bağlanabilir; veri tamamen yerel.',
    highlight: 'Cursor\'un açık kaynak klonu, veri dışarı çıkmaz',
    tags: ['Ücretsiz', 'Açık Kaynak', 'Yerel Çalışır', 'Gizlilik Odaklı'],
    category: 'kod',
    openSource: true,
  },
  {
    name: 'OpenAI Codex CLI',
    website: 'https://github.com/openai/codex',
    description: 'OpenAI\'ın terminal üzerinden kodlama yapabilen açık kaynak ajan. Kod yazar, test çalıştırır, hataları düzeltir — tümü komut satırından.',
    highlight: 'Terminal\'den tam otonom kod yazma ve test döngüsü',
    tags: ['Açık Kaynak', 'API', 'Ücretsiz'],
    category: 'kod',
    openSource: true,
  },
  {
    name: 'Gemini CLI',
    website: 'https://github.com/google-gemini/gemini-cli',
    description: 'Google\'ın terminal tabanlı AI kodlama asistanı. Gemini Pro\'nun 1M token bağlamını doğrudan CLI üzerinden kullanarak büyük kod tabanlarını analiz eder.',
    highlight: '1M token bağlamla büyük projeyi terminalden analiz et',
    tags: ['Açık Kaynak', 'Ücretsiz', 'API'],
    category: 'kod',
    openSource: true,
  },
  {
    name: 'Warp Terminal',
    website: 'https://warp.dev',
    description: 'AI entegre akıllı terminal. Komutları doğal dille yaz, hata mesajlarını otomatik açıklat, terminal çıktılarını AI ile analiz et.',
    highlight: 'Doğal dille komut yaz, hataları AI ile anında çöz',
    tags: ['Ücretsiz', 'Hızlı'],
    category: 'kod',
  },
  {
    name: 'TabbyML',
    website: 'https://tabby.tabbyml.com',
    description: 'Kendi sunucuna kur, tamamen self-hosted çalışan AI kod tamamlama aracı. GitHub Copilot\'un şirket içi gizlilik ihtiyacını karşılayan ücretsiz alternatifi.',
    highlight: 'Self-hosted Copilot: kod hiç dışarı çıkmaz',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Gizlilik Odaklı', 'Kurumsal'],
    category: 'kod',
    openSource: true,
  },
  {
    name: 'Firebase Studio',
    website: 'https://firebase.google.com/studio',
    description: 'Google\'ın bulut tabanlı AI-first geliştirme ortamı. Tarayıcıda tam uygulama geliştir, Firebase ile anlık dağıt; Gemini entegre kod asistanı dahil.',
    highlight: 'Tarayıcıda AI ile uygulama geliştir, anında deploy',
    tags: ['Ücretsiz', 'Tarayıcı', 'API'],
    category: 'kod',
  },
  {
    name: 'opencode',
    website: 'https://opencode.ai',
    description: 'Terminal üzerinden çalışan, çoklu AI sağlayıcısına bağlanabilen açık kaynak kodlama ajanı. Claude, GPT-4 ve yerel modellerle çalışır.',
    highlight: 'Herhangi bir AI modeline bağlanabilen terminal koding ajanı',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır'],
    category: 'kod',
    openSource: true,
  },
  // Bizim katkımız ─────────────────────────────────────────────────────────────
  {
    name: 'Aider',
    website: 'https://aider.chat',
    description: 'Terminal tabanlı, git ile tam entegre AI çift programlama aracı. Claude ve GPT-4 ile konuşarak kod yazar, commit oluşturur, refactor yapar.',
    highlight: 'Git entegre terminal: konuş, yaz, commit — döngüsü tam',
    tags: ['Açık Kaynak', 'Ücretsiz', 'API'],
    category: 'kod',
    openSource: true,
    addedByUs: true,
  },
  {
    name: 'Continue.dev',
    website: 'https://continue.dev',
    description: 'VS Code ve JetBrains için açık kaynak AI kod asistanı eklentisi. Herhangi bir modele (yerel veya API) bağlanır; ChatGPT Copilot\'a ücretsiz ve esnek alternatif.',
    highlight: 'Herhangi bir modele bağlan: Ollama, Claude, GPT — seçim sende',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır'],
    category: 'kod',
    openSource: true,
    addedByUs: true,
  },
]

// ─── GÖRSEL ÜRETİM ────────────────────────────────────────────────────────────
export const GORSEL_ALTERNATIVES: Alternative[] = [
  {
    name: 'Ideogram',
    website: 'https://ideogram.ai',
    description: 'Görsel içinde metin oluşturmada sektörün en iyisi. Poster, logo, tipografik tasarım ve sosyal medya içerikleri için metinlerin doğru yazılması kritik olduğunda tercih edilir.',
    highlight: 'AI görselinde doğru yazı: poster ve logo için rakipsiz',
    tags: ['Ücretsiz', 'Hızlı'],
    category: 'gorsel',
  },
  {
    name: 'FLUX.2 (Black Forest Labs)',
    website: 'https://flux1.ai',
    description: 'Black Forest Labs\'ın geliştirdiği açık kaynak görsel üretim modeli. Gerçekçilik ve prompt uyumu açısından Midjourney\'e rakip, tamamen ücretsiz ve yerel çalıştırılabilir.',
    highlight: 'Midjourney kalitesi, açık kaynak ve yerel çalışır',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır'],
    category: 'gorsel',
    openSource: true,
  },
  {
    name: 'Google Imagen 3',
    website: 'https://imagen.research.google',
    description: 'Google DeepMind\'ın fotorealistik görüntü üretim modeli. Vertex AI üzerinden API erişimi; Google altyapısıyla ölçeklenebilir kurumsal görsel üretimi.',
    highlight: 'Google altyapısında fotorealistik görsel üretimi',
    tags: ['API', 'Kurumsal'],
    category: 'gorsel',
  },
  {
    name: 'InvokeAI',
    website: 'https://invoke.ai',
    description: 'Stable Diffusion tabanlı, yerel çalışan tam özellikli görsel üretim platformu. Inpainting, outpainting, ControlNet ve model yönetimi dahil eksiksiz yaratıcı araç seti.',
    highlight: 'Yerel Stable Diffusion stüdyosu: tam kontrol',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz'],
    category: 'gorsel',
    openSource: true,
  },
  {
    name: 'Janus Pro (DeepSeek)',
    website: 'https://github.com/deepseek-ai/Janus',
    description: 'DeepSeek\'in hem görsel anlama hem görsel üretim yapabilen birleşik çok modlu modeli. Açık kaynak, yerel çalıştırılabilir.',
    highlight: 'Görsel anlama + üretimi aynı modelde, açık kaynak',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz'],
    category: 'gorsel',
    openSource: true,
  },
  {
    name: 'Craiyon',
    website: 'https://craiyon.com',
    description: 'DALL-E Mini\'nin geliştirilmiş versiyonu. Tamamen ücretsiz, kayıt gerektirmez; hız ve kalite düşük olsa da hızlı fikir testi için pratik.',
    highlight: 'Kayıt yok, tamamen ücretsiz, anlık deneme',
    tags: ['Ücretsiz', 'Tarayıcı'],
    category: 'gorsel',
  },
  {
    name: 'Krita AI Diffusion',
    website: 'https://github.com/Acly/krita-ai-diffusion',
    description: 'Açık kaynak Krita resim programına Stable Diffusion entegre eden eklenti. Profesyonel dijital sanatçılar için mevcut iş akışına AI\'ı sorunsuz ekler.',
    highlight: 'Krita ile AI: profesyonel dijital sanat iş akışı',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz'],
    category: 'gorsel',
    openSource: true,
  },
  {
    name: 'Qwen Image',
    website: 'https://huggingface.co/Qwen',
    description: 'Alibaba\'nın Qwen-VL ve görsel üretim modelleri. Çince metin içeren görseller ve Asya pazarı görsel içerikleri için özel optimize.',
    highlight: 'Çince metin içeren görsel üretiminde en iyi seçenek',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Çok Dilli'],
    category: 'gorsel',
    openSource: true,
  },
  // Bizim katkımız ─────────────────────────────────────────────────────────────
  {
    name: 'Kling AI',
    website: 'https://kling.kuaishou.com',
    description: 'Kuaishou\'nun geliştirdiği, görüntü ve videodan yüksek kaliteli görsel üretim platformu. Özellikle Asya pazarı görsel estetiğinde ve karakter tutarlılığında güçlü.',
    highlight: 'Karakter tutarlılığı ve Asya estetiğinde rakipsiz',
    tags: ['Ücretsiz', 'Hızlı', 'Çok Dilli'],
    category: 'gorsel',
    addedByUs: true,
  },
  {
    name: 'Recraft V3',
    website: 'https://recraft.ai',
    description: 'Vektör görsel, ikon, illüstrasyon ve marka kimliği tasarımı için özelleşmiş AI tasarım platformu. Stil tutarlılığı ve SVG çıktısı ile tasarımcılara özel.',
    highlight: 'SVG vektör ve marka kimliği için özelleşmiş AI tasarım',
    tags: ['Ücretsiz', 'API', 'Kurumsal'],
    category: 'gorsel',
    addedByUs: true,
  },
]

// ─── SES & KONUŞMA ────────────────────────────────────────────────────────────
export const SES_ALTERNATIVES: Alternative[] = [
  {
    name: 'Kokoro TTS',
    website: 'https://huggingface.co/hexgrad/Kokoro-82M',
    description: 'Sadece 82M parametre ile etkileyici ses kalitesi sunan, Apache 2.0 lisanslı küçük TTS modeli. Yerel çalıştırılabilir, ticari kullanıma açık.',
    highlight: '82M parametre, yüksek kalite, tamamen ücretsiz ve yerel',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz'],
    category: 'ses',
    openSource: true,
  },
  {
    name: 'Voxtral (Mistral)',
    website: 'https://mistral.ai/news/voxtral',
    description: 'Mistral\'ın ses anlama modeli. Konuşmadan metin, ses tanıma ve çok dilli transkripsiyon için Avrupa merkezli gizlilik güvenceleri ile.',
    highlight: 'Avrupa gizliliği ile ses tanıma ve transkripsiyon',
    tags: ['API', 'Çok Dilli', 'Gizlilik Odaklı'],
    category: 'ses',
  },
  {
    name: 'Chatterbox TTS',
    website: 'https://github.com/resemble-ai/chatterbox',
    description: 'Resemble AI\'ın açık kaynak TTS modeli. Ses klonlama ve duygusal tonlama özellikli, yerel çalıştırılabilir.',
    highlight: 'Açık kaynak ses klonlama, duygusal tonlama',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz'],
    category: 'ses',
    openSource: true,
  },
  {
    name: 'TTSMaker',
    website: 'https://ttsmaker.com',
    description: '200\'den fazla ses ve 50+ dil desteğiyle tamamen ücretsiz TTS hizmeti. MP3 çıktı, Türkçe dahil, kayıt gerektirmez.',
    highlight: '200+ ses, Türkçe dahil 50+ dil, kayıtsız ücretsiz',
    tags: ['Ücretsiz', 'Türkçe Destekli', 'Tarayıcı'],
    category: 'ses',
  },
  {
    name: 'OpenAI Voice Engine',
    website: 'https://openai.com/blog/navigating-the-challenges-and-opportunities-of-synthetic-voices',
    description: 'OpenAI\'ın 15 saniyelik ses örneğinden klonlama yapan TTS altyapısı. ChatGPT Advanced Voice Mode\'un temelinde yatar; API olarak erişim kısıtlı.',
    highlight: '15 saniye örneğiyle profesyonel ses klonlama',
    tags: ['API', 'Ücretli'],
    category: 'ses',
  },
  {
    name: 'VoiceCraft',
    website: 'https://github.com/jasonppy/VoiceCraft',
    description: 'Ses düzenleme ve klonlama için akademik araştırma modeli. Mevcut konuşma kaydındaki belirli kelimeleri değiştirip seslendirmeyi sürdürebilir.',
    highlight: 'Kayıttaki tek kelimeyi değiştir, ses sürekliliği bozulmaz',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır'],
    category: 'ses',
    openSource: true,
  },
  {
    name: 'Audiomatic',
    website: 'https://audiomatic.ai',
    description: 'Metin, ses veya PDF\'den otomatik podcast ve sesli içerik üretimi. İçerik üreticileri için yapay zeka destekli tam prodüksiyon platformu.',
    highlight: 'PDF → podcast: içeriği otomatik sesli yayına çevir',
    tags: ['Ücretsiz', 'Hızlı', 'Çok Dilli'],
    category: 'ses',
  },
  // Bizim katkımız ─────────────────────────────────────────────────────────────
  {
    name: 'Parler TTS',
    website: 'https://huggingface.co/parler-tts',
    description: 'HuggingFace\'in açık kaynak TTS modeli. Doğal dil talimatlarıyla ses stilini tanımlayabilirsin: "Orta yaşlı kadın sesi, yüksek kalite mikrofon, düşük sesle".',
    highlight: 'Doğal dil ile ses stilini tanımla: en esnek açık TTS',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır'],
    category: 'ses',
    openSource: true,
    addedByUs: true,
  },
  {
    name: 'Fish Audio',
    website: 'https://fish.audio',
    description: 'Topluluk tarafından paylaşılan ses modelleriyle herhangi bir ünlü veya karakter sesinde TTS ve klonlama yapabilen platform. Türkçe ses modelleri de mevcut.',
    highlight: 'Topluluk ses modelleri: Türkçe dahil her dil ve karakter',
    tags: ['Ücretsiz', 'Türkçe Destekli', 'Çok Dilli'],
    category: 'ses',
    addedByUs: true,
  },
]

// ─── YEREL & GİZLİLİK ODAKLI ─────────────────────────────────────────────────
export const YEREL_ALTERNATIVES: Alternative[] = [
  {
    name: 'Ollama',
    website: 'https://ollama.ai',
    description: 'Llama, Mistral, Qwen, Gemma ve onlarca modeli tek komutla indirip çalıştıran yerel model yöneticisi. `ollama run llama3` yazman yeterli — internet bağlantısı sonrasında gerekmez.',
    highlight: 'Tek komutla her açık modeli yerel çalıştır',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Gizlilik Odaklı'],
    category: 'yerel',
    openSource: true,
  },
  {
    name: 'Jan.ai',
    website: 'https://jan.ai',
    description: 'ChatGPT arayüzünü taklit eden, tamamen yerel çalışan masaüstü AI platformu. Modelleri tek tıkla indir, tüm konuşmalar yerel kalır, internet bağlantısı gerekmez.',
    highlight: 'ChatGPT\'nin yerel versiyonu — veri hiç dışarı çıkmaz',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Gizlilik Odaklı'],
    category: 'yerel',
    openSource: true,
  },
  {
    name: 'AnythingLLM',
    website: 'https://anythingllm.com',
    description: 'Şirket içi dokümanları (PDF, Word, Excel, web) yerel AI ile sorgulayan kurumsal RAG platformu. Docker ile kurum sunucusuna kur, veri dışarı çıkmaz.',
    highlight: 'Şirket dokümanlarını yerel AI ile güvenle sorgula',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Kurumsal', 'Gizlilik Odaklı'],
    category: 'yerel',
    openSource: true,
  },
  {
    name: 'PrivateGPT',
    website: 'https://privategpt.io',
    description: '100% yerel çalışan, belge ingestion ve sorgulama yapabilen açık kaynak RAG sistemi. Sağlık, hukuk ve finans sektörü için veri güvenliği kritik durumlarda tercih edilir.',
    highlight: '%100 yerel RAG: belge sorgulama, hiç dışarı çıkmaz',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Gizlilik Odaklı', 'Kurumsal'],
    category: 'yerel',
    openSource: true,
  },
  {
    name: 'LibreChat',
    website: 'https://librechat.ai',
    description: 'Self-hosted ChatGPT klonu. OpenAI, Anthropic, Google, yerel Ollama modelleri ve daha fazlasına tek arayüzden erişim. Ekip için kullanıcı yönetimi ve konuşma geçmişi.',
    highlight: 'Kendi sunucunda çok kullanıcılı ChatGPT klonu',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Kurumsal'],
    category: 'yerel',
    openSource: true,
  },
  {
    name: 'LobeChat',
    website: 'https://lobechat.com',
    description: 'Modern UI\'lı, eklenti destekli self-hosted AI asistan. Plugin ekosistemi ile web arama, görsel üretim ve araç kullanımı eklenebilir. Docker ile kolayca kurulur.',
    highlight: 'Eklenti ekosistemi ile genişletilebilir self-hosted AI',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz'],
    category: 'yerel',
    openSource: true,
  },
  {
    name: 'Text generation web UI',
    website: 'https://github.com/oobabooga/text-generation-webui',
    description: 'Oobabooga tarafından geliştirilen, yerel modeller için en kapsamlı web arayüzü. Llama, Mistral, Falcon ve GPTQ/GGUF formatlarını destekler; gelişmiş örnekleme ayarları mevcut.',
    highlight: 'Yerel model için en gelişmiş kontrol paneli',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz'],
    category: 'yerel',
    openSource: true,
  },
  {
    name: 'Backyard AI',
    website: 'https://backyard.ai',
    description: 'Yerel modeller üzerinde karakter ve kişilik tanımlaması yapabilen, oyun ve yaratıcı yazarlık odaklı AI platform. NSFW filtresi devre dışı bırakılabilir.',
    highlight: 'Yerel modelle tam özelleştirilebilir AI karakter',
    tags: ['Ücretsiz', 'Yerel Çalışır', 'Açık Kaynak'],
    category: 'yerel',
  },
  {
    name: 'Khoj',
    website: 'https://khoj.dev',
    description: 'Kişisel AI asistanı ve araştırma yardımcısı; kendi notlarınla, dosyalarınla ve web ile konuşmanızı sağlar. Self-hosted veya bulut seçeneği mevcut.',
    highlight: 'Kendi notların + web + dosyaların üzerinde AI arama',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Akademik'],
    category: 'yerel',
    openSource: true,
  },
  // Bizim katkımız ─────────────────────────────────────────────────────────────
  {
    name: 'Open WebUI',
    website: 'https://openwebui.com',
    description: 'Ollama için geliştirilmiş, özellik bakımından ChatGPT\'yi geçen self-hosted web arayüzü. Çoklu model, konuşma geçmişi, RAG, eklentiler ve kullanıcı yönetimi dahil.',
    highlight: 'Ollama\'nın ChatGPT\'den iyi arayüzü: RAG dahil',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Gizlilik Odaklı'],
    category: 'yerel',
    openSource: true,
    addedByUs: true,
  },
  {
    name: 'GPT4All',
    website: 'https://gpt4all.io',
    description: 'Nomic AI\'ın herhangi bir bilgisayarda çalışabilen yerel AI platformu. Doküman analizi, yerel RAG ve CPU üzerinde bile çalışabilen optimize modeller.',
    highlight: 'Eski bilgisayarda bile CPU ile yerel AI çalıştır',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Gizlilik Odaklı'],
    category: 'yerel',
    openSource: true,
    addedByUs: true,
  },
]

// ─── AÇIK KAYNAK MODELLER ─────────────────────────────────────────────────────
export const ACIK_KAYNAK: Alternative[] = [
  {
    name: 'Meta Llama 3.x',
    website: 'https://llama.meta.com',
    description: 'Meta\'nın Llama 3.1 (405B), 3.2 ve 3.3 modelleri araştırma ve ticari kullanıma açık. 128K token bağlam, 8 dil desteği; yerel veya bulut altyapısında çalıştırılabilir.',
    highlight: '405B parametreli GPT-4 seviyesi model, ticari lisans serbest',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır', 'Çok Dilli'],
    category: 'acik-kaynak',
    openSource: true,
  },
  {
    name: 'Google Gemma 3',
    website: 'https://ai.google.dev/gemma',
    description: 'Google\'ın küçük boyutlu, etkin açık kaynak model ailesi. 2B, 7B, 27B parametreli versiyonlar; mobil ve edge cihazlarda bile çalışabilir. Apache 2.0 lisanslı.',
    highlight: 'Mobil ve edge cihazda çalışan Google\'ın açık modeli',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır', 'Mobil'],
    category: 'acik-kaynak',
    openSource: true,
  },
  {
    name: 'DeepSeek R1',
    website: 'https://github.com/deepseek-ai/DeepSeek-R1',
    description: 'Açık kaynak zincir-düşünme (chain-of-thought) modeli. Matematik, fizik ve kod gibi muhakeme gerektiren görevlerde o1-preview ile yarışır; MIT lisanslı.',
    highlight: 'o1 seviyesi muhakeme, MIT lisanslı, tamamen ücretsiz',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır', 'Akademik'],
    category: 'acik-kaynak',
    openSource: true,
  },
  {
    name: 'Mistral 7B / Mixtral',
    website: 'https://mistral.ai',
    description: 'Avrupa merkezli Mistral AI\'ın açık ağırlıklı modelleri. Mixtral 8x7B, Mixture of Experts mimarisiyle aynı kalitede çok daha az hesaplama kullanır.',
    highlight: 'Mixture of Experts: GPT-3.5 kalitesi, 4x daha az güç',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır', 'Çok Dilli'],
    category: 'acik-kaynak',
    openSource: true,
  },
  {
    name: 'Open R1 (Hugging Face)',
    website: 'https://github.com/huggingface/open-r1',
    description: 'HuggingFace\'in DeepSeek R1\'in eğitim sürecini tam şeffaflıkla yeniden üretme projesi. Açık kaynak muhakeme modeli geliştirme için referans.',
    highlight: 'DeepSeek R1 eğitim sürecini açık yeniden üretme',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Akademik'],
    category: 'acik-kaynak',
    openSource: true,
  },
  {
    name: 'Microsoft Phi-4',
    website: 'https://huggingface.co/microsoft/phi-4',
    description: 'Microsoft\'un küçük ama yetenekli Phi model ailesi. 14B parametre ile birçok büyük modeli geçen benchmark skorları; akıllı telefon ve edge için optimize.',
    highlight: '14B parametre ile büyük modelleri geçen benchmark performansı',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır', 'Hızlı'],
    category: 'acik-kaynak',
    openSource: true,
  },
  {
    name: 'Qwen 2.5 (Alibaba)',
    website: 'https://qwenlm.github.io',
    description: 'Alibaba\'nın 0.5B\'den 72B\'ye kadar boyut aralığındaki açık kaynak model ailesi. Türkçe dahil 29 dilde yüksek performans; kod, matematik ve uzun bağlam güçlü.',
    highlight: '0.5B-72B arası, Türkçe dahil 29 dil, kod ve matematik',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır', 'Türkçe Destekli', 'Çok Dilli'],
    category: 'acik-kaynak',
    openSource: true,
  },
  // Bizim katkımız ─────────────────────────────────────────────────────────────
  {
    name: 'Cohere Aya (Çok Dilli)',
    website: 'https://cohere.com/research/aya',
    description: 'Türkçe dahil 101 dili destekleyen açık kaynak çok dilli model. Düşük kaynaklı dillerde diğer büyük modelleri geçen benzersiz çok dilli kapsam.',
    highlight: 'Türkçe dahil 101 dil: az kaynaklı dillerde rakipsiz',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Türkçe Destekli', 'Çok Dilli', 'Akademik'],
    category: 'acik-kaynak',
    openSource: true,
    addedByUs: true,
  },
  {
    name: 'Falcon 3 (TII)',
    website: 'https://falconllm.tii.ae',
    description: 'Abu Dabi\'deki Teknoloji İnovasyon Enstitüsü\'nün geliştirdiği, Orta Doğu dilleri ve Arapça için optimize açık kaynak model. Egemen AI altyapısı için referans.',
    highlight: 'Arapça ve Orta Doğu dilleri için optimize egemen AI',
    tags: ['Açık Kaynak', 'Ücretsiz', 'Yerel Çalışır', 'Çok Dilli'],
    category: 'acik-kaynak',
    openSource: true,
    addedByUs: true,
  },
]

// ─── ARAŞTIRMA ARAÇLARI (Dosyadan + Katkı) ───────────────────────────────────
export const ARASTIRMA_ALTERNATIVES: Alternative[] = [
  {
    name: 'Arena AI (LMSYS)',
    website: 'https://lmarena.ai',
    description: 'UC Berkeley\'in tarafsız model karşılaştırma platformu. İki anonim AI\'ya aynı soruyu sor, hangisi daha iyi yanıt verdi oy ver — ELO sıralamasıyla gerçek güç ölçümü.',
    highlight: 'Hangi AI daha iyi? Tarafsız bilimsel ELO sıralaması',
    tags: ['Ücretsiz', 'Akademik'],
    category: 'arastirma',
  },
  {
    name: 'Farfalle',
    website: 'https://github.com/rashadphz/farfalle',
    description: 'Perplexity\'nin yerel ve açık kaynak klonu. Kendi API anahtarınla veya yerel Ollama modeliyle kaynaklı web araması yapan self-hosted araştırma asistanı.',
    highlight: 'Perplexity\'nin self-hosted açık kaynak alternatifi',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Akademik'],
    category: 'arastirma',
    openSource: true,
  },
  {
    name: 'Khoj',
    website: 'https://khoj.dev',
    description: 'Kişisel araştırma asistanı: kendi notlarını, PDF\'lerini ve web\'i birlikte sorgular. Obsidian, Notion ve GitHub entegrasyonu ile kişisel bilgi tabanı üzerine AI.',
    highlight: 'Notların + PDF\'lerin + web: kişisel AI araştırma asistanı',
    tags: ['Açık Kaynak', 'Yerel Çalışır', 'Ücretsiz', 'Akademik'],
    category: 'arastirma',
    openSource: true,
  },
  // Bizim katkımız ─────────────────────────────────────────────────────────────
  {
    name: 'Tavily AI',
    website: 'https://tavily.com',
    description: 'AI ajanları için özel tasarlanmış gerçek zamanlı web arama API\'si. LangChain, LlamaIndex ve AutoGen ile entegre; araştırma akışlarında Perplexity\'ye alternatif.',
    highlight: 'AI ajan araştırma akışları için gerçek zamanlı arama API',
    tags: ['API', 'Akademik', 'Ücretsiz'],
    category: 'arastirma',
    addedByUs: true,
  },
  {
    name: 'Storm (Stanford)',
    website: 'https://storm.genie.stanford.edu',
    description: 'Stanford\'ın geliştirdiği, herhangi bir konuda Wikipedia benzeri kapsamlı makale üreten AI araştırma sistemi. Çok kaynaktan sentez, atıflı çıktı.',
    highlight: 'Stanford\'ın AI\'ı: konudan Wikipedia kaliteli makale üret',
    tags: ['Ücretsiz', 'Akademik', 'Açık Kaynak'],
    category: 'arastirma',
    openSource: true,
    addedByUs: true,
  },
  {
    name: 'Perplexity Labs',
    website: 'https://labs.perplexity.ai',
    description: 'Perplexity\'nin deneysel model ve özelliklerini önceden test etme ortamı. Yeni Sonar modellerini ücretsiz olarak deneyebilirsiniz.',
    highlight: 'Perplexity\'nin en yeni modellerini ücretsiz erken test et',
    tags: ['Ücretsiz', 'Akademik'],
    category: 'arastirma',
  },
]

// ─── KATEGORİ META ────────────────────────────────────────────────────────────
export const ALT_CATEGORIES = [
  {
    id: 'sohbet' as AltCategory,
    label: 'Sohbet Asistanları',
    description: 'Genel amaçlı AI sohbet ve asistan platformları',
    icon: '💬',
    mainTool: 'ChatGPT',
    mainToolTagline: 'OpenAI\'ın dünyaca ünlü AI sohbet asistanı',
    mainToolWebsite: 'https://chatgpt.com',
    color: 'blue',
    data: SOHBET_ALTERNATIVES,
  },
  {
    id: 'kod' as AltCategory,
    label: 'Kodlama Araçları',
    description: 'AI destekli kod tamamlama, üretme ve geliştirme ortamları',
    icon: '⌨️',
    mainTool: 'GitHub Copilot',
    mainToolTagline: 'GitHub\'ın AI destekli kod tamamlama aracı',
    mainToolWebsite: 'https://github.com/features/copilot',
    color: 'amber',
    data: KOD_ALTERNATIVES,
  },
  {
    id: 'gorsel' as AltCategory,
    label: 'Görsel Üretim',
    description: 'Metinden görsel üreten AI araçları',
    icon: '🎨',
    mainTool: 'Midjourney',
    mainToolTagline: 'Prompt\'tan sanatsal görsel üreten en popüler AI',
    mainToolWebsite: 'https://midjourney.com',
    color: 'pink',
    data: GORSEL_ALTERNATIVES,
  },
  {
    id: 'ses' as AltCategory,
    label: 'Ses & Konuşma',
    description: 'TTS, ses klonlama ve konuşmadan metne araçları',
    icon: '🎙️',
    mainTool: 'ElevenLabs',
    mainToolTagline: 'Gerçekçi ses klonlama ve metin okuma platformu',
    mainToolWebsite: 'https://elevenlabs.io',
    color: 'emerald',
    data: SES_ALTERNATIVES,
  },
  {
    id: 'yerel' as AltCategory,
    label: 'Yerel & Gizlilik',
    description: 'İnternetsiz, tamamen yerel çalışan AI araçları',
    icon: '🔒',
    mainTool: 'Bulut AI\'lar',
    mainToolTagline: 'ChatGPT, Claude, Gemini — verileriniz buluta gidiyor',
    mainToolWebsite: '',
    color: 'violet',
    data: YEREL_ALTERNATIVES,
  },
  {
    id: 'acik-kaynak' as AltCategory,
    label: 'Açık Kaynak Modeller',
    description: 'İndirilip yerel çalıştırılabilen, ticari kullanıma açık LLM\'ler',
    icon: '🤖',
    mainTool: 'GPT-4 / Claude',
    mainToolTagline: 'Aylık abonelik gerektiren kapalı kaynak büyük modeller',
    mainToolWebsite: '',
    color: 'indigo',
    data: ACIK_KAYNAK,
  },
  {
    id: 'arastirma' as AltCategory,
    label: 'Araştırma Araçları',
    description: 'Kaynaklı arama, akademik sentez ve araştırma asistanları',
    icon: '🔬',
    mainTool: 'Perplexity',
    mainToolTagline: 'Kaynaklı web araması yapan AI arama motoru',
    mainToolWebsite: 'https://perplexity.ai',
    color: 'cyan',
    data: ARASTIRMA_ALTERNATIVES,
  },
]
